name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.2
  flutter_animate: ^4.0.3
  shared_preferences: ^2.1.1
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.1.0
  photo_view: ^0.14.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/pertanyaan_1.png
    - assets/images/background.jpeg
    - assets/images/penjumlahan.png
    - assets/images/proklamasi-indonesia.jpg
    - assets/images/sungai-amazon.jpeg
    - assets/images/angin-tornado.jpg
    - assets/images/perjanjian-versailes.jpg

